dist: bionic
language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.10
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors

script:
  - MIX_ENV=test mix test

after_script:
  - MIX_ENV=docs mix do deps.get, deps.compile
  - MIX_ENV=docs mix inch.report

cache:
  directories:
    - ~/.mix
    - ~/.hex
    - _build

