dist: bionic
language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.10
env:
  - MIX_ENV=test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
