 %HTTPoison.Response{
   body: %{
     "active_lock_reason" => nil,
     "assignee" => nil,
     "assignees" => [],
     "author_association" => "OWNER",
     "body" => "",
     "closed_at" => "2019-04-24T18:51:17Z",
     "closed_by" => %{
       "avatar_url" => "https://avatars2.githubusercontent.com/u/5345745?v=4",
       "events_url" => "https://api.github.com/users/Qqwy/events{/privacy}",
       "followers_url" => "https://api.github.com/users/Qqwy/followers",
       "following_url" => "https://api.github.com/users/Qqwy/following{/other_user}",
       "gists_url" => "https://api.github.com/users/Qqwy/gists{/gist_id}",
       "gravatar_id" => "",
       "html_url" => "https://github.com/Qqwy",
       "id" => 5345745,
       "login" => "Qqwy",
       "node_id" => "MDQ6VXNlcjUzNDU3NDU=",
       "organizations_url" => "https://api.github.com/users/Qqwy/orgs",
       "received_events_url" => "https://api.github.com/users/Qqwy/received_events",
       "repos_url" => "https://api.github.com/users/Qqwy/repos",
       "site_admin" => false,
       "starred_url" => "https://api.github.com/users/Qqwy/starred{/owner}{/repo}",
       "subscriptions_url" => "https://api.github.com/users/Qqwy/subscriptions",
       "type" => "User",
       "url" => "https://api.github.com/users/Qqwy"
     },
     "comments" => 0,
     "comments_url" => "https://api.github.com/repos/Qqwy/elixir-specify/issues/1/comments",
     "created_at" => "2019-04-24T18:50:31Z",
     "events_url" => "https://api.github.com/repos/Qqwy/elixir-specify/issues/1/events",
     "html_url" => "https://github.com/Qqwy/elixir-specify/pull/1",
     "id" => 436853279,
     "labels" => [],
     "labels_url" => "https://api.github.com/repos/Qqwy/elixir-specify/issues/1/labels{/name}",
     "locked" => false,
     "milestone" => nil,
     "node_id" => "MDExOlB1bGxSZXF1ZXN0MjczMjU2ODY3",
     "number" => 1,
     "pull_request" => %{
       "diff_url" => "https://github.com/Qqwy/elixir-specify/pull/1.diff",
       "html_url" => "https://github.com/Qqwy/elixir-specify/pull/1",
       "patch_url" => "https://github.com/Qqwy/elixir-specify/pull/1.patch",
       "url" => "https://api.github.com/repos/Qqwy/elixir-specify/pulls/1"
     },
     "repository_url" => "https://api.github.com/repos/Qqwy/elixir-specify",
     "state" => "closed",
     "title" => "Name Change: Confy -> Specify",
     "updated_at" => "2019-04-24T18:51:17Z",
     "url" => "https://api.github.com/repos/Qqwy/elixir-specify/issues/1",
     "user" => %{
       "avatar_url" => "https://avatars2.githubusercontent.com/u/5345745?v=4",
       "events_url" => "https://api.github.com/users/Qqwy/events{/privacy}",
       "followers_url" => "https://api.github.com/users/Qqwy/followers",
       "following_url" => "https://api.github.com/users/Qqwy/following{/other_user}",
       "gists_url" => "https://api.github.com/users/Qqwy/gists{/gist_id}",
       "gravatar_id" => "",
       "html_url" => "https://github.com/Qqwy",
       "id" => 5345745,
       "login" => "Qqwy",
       "node_id" => "MDQ6VXNlcjUzNDU3NDU=",
       "organizations_url" => "https://api.github.com/users/Qqwy/orgs",
       "received_events_url" => "https://api.github.com/users/Qqwy/received_events",
       "repos_url" => "https://api.github.com/users/Qqwy/repos",
       "site_admin" => false,
       "starred_url" => "https://api.github.com/users/Qqwy/starred{/owner}{/repo}",
       "subscriptions_url" => "https://api.github.com/users/Qqwy/subscriptions",
       "type" => "User",
       "url" => "https://api.github.com/users/Qqwy"
     }
   },
   headers: [
     {"date", "Tue, 16 Jun 2020 14:43:18 GMT"},
     {"content-type", "application/json; charset=utf-8"},
     {"server", "GitHub.com"},
     {"status", "200 OK"},
     {"cache-control", "public, max-age=60, s-maxage=60"},
     {"vary",
      "Accept, Accept-Encoding, Accept, X-Requested-With, Accept-Encoding"},
     {"etag", "W/\"4c964c0a49ab2d4a4585e2796c88b21a\""},
     {"last-modified", "Tue, 09 Jun 2020 14:34:48 GMT"},
     {"x-github-media-type", "github.v3; format=json"},
     {"access-control-expose-headers",
      "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset"},
     {"access-control-allow-origin", "*"},
     {"strict-transport-security",
      "max-age=31536000; includeSubdomains; preload"},
     {"x-frame-options", "deny"},
     {"x-content-type-options", "nosniff"},
     {"x-xss-protection", "1; mode=block"},
     {"referrer-policy",
      "origin-when-cross-origin, strict-origin-when-cross-origin"},
     {"content-security-policy", "default-src 'none'"},
     {"X-Ratelimit-Limit", "60"},
     {"X-Ratelimit-Remaining", "58"},
     {"X-Ratelimit-Reset", "1592322174"},
     {"Accept-Ranges", "bytes"},
     {"Content-Length", "2841"},
     {"X-GitHub-Request-Id", "C4C7:34EAF:3DCA1D:4C3E4F:5EE8DA6F"}
   ],
   request: %HTTPoison.Request{
     body: "\"\\\"\\\"\"",
     headers: [{"User-agent", "tentacat"}],
     method: :get,
     options: [],
     params: %{},
     url: "https://api.github.com/repos/Qqwy/elixir-specify/issues/1"
   },
   request_url: "https://api.github.com/repos/Qqwy/elixir-specify/issues/1",
   status_code: 200
 }}